#!/usr/bin/env python3
"""
One-time: pull the landing page's hand-written "Featured projects" cards out of index.html
into per-project teaser files, and replace the region with generator markers.

  cv/projects/<id>.teaser.html   the short teaser body for the index (one per featured project)

Teaser files use the SAME `../assets/...` path convention as the full card bodies; the
generator rewrites them to root-relative `assets/...` when it injects them into index.html.
Internal `cv/#projects/x` links are left as-is (correct from the site root).

Run once:  python3 tools/extract_index_teasers.py
"""
import os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(ROOT, "index.html")
OUT = os.path.join(ROOT, "cv", "projects")

_TAG = re.compile(r'<!--|<div\b|</div>')
def match_div_end(text, pos):
    depth, i, n = 0, pos, len(text)
    while i < n:
        m = _TAG.search(text, i)
        if not m:
            return n
        tok = m.group(0)
        if tok == '<!--':
            j = text.find('-->', m.end()); i = j + 3 if j != -1 else n
        elif tok == '</div>':
            depth -= 1; i = m.end()
            if depth == 0:
                return i
        else:
            depth += 1; i = m.end()
    return n

def main():
    s = open(INDEX, encoding="utf-8").read()
    sc = re.search(r'<div id\s*=\s*"select_content">', s)
    region_start = sc.end()
    # region of cards = from first card wrapper to the </div> that closes #select_content
    sc_end = match_div_end(s, sc.start())            # end of #select_content div
    inner = s[region_start:sc_end - len('</div>')]   # inside #select_content

    # find each card wrapper <div class="sortable-div ...">...</div> and its .well body
    ids, first, last = [], None, None
    i = 0
    while i < len(inner):
        if inner.startswith('<!--', i):
            j = inner.find('-->', i); i = j + 3 if j != -1 else len(inner); continue
        m = re.match(r'<div class="sortable-div [^"]*">', inner[i:])
        if m:
            end = match_div_end(inner, i)
            block = inner[i:end]
            wm = re.search(r'<div class="well" name="([^"]*)" id="([^"]*)">', block)
            if wm:
                wid = wm.group(2)
                well_abs = i + wm.start()
                body = inner[i + wm.end(): match_div_end(inner, well_abs) - len('</div>')]
                body = body.replace('="assets/', '="../assets/').strip("\n")
                open(os.path.join(OUT, wid + ".teaser.html"), "w", encoding="utf-8").write(body + "\n")
                ids.append(wid)
                if first is None:
                    first = region_start + i
                last = region_start + end
            i = end; continue
        i += 1

    # replace the cards region with generator markers
    marker = ('\n\n                <!-- FEATURED:START  (generated by tools/build_projects.py from '
              'cv/projects/<id>.teaser.html — do not edit here) -->\n'
              '                <!-- FEATURED:END -->\n\n            ')
    new = s[:first] + marker.lstrip('\n') + s[last:]
    open(INDEX, "w", encoding="utf-8").write(new)
    print("extracted teasers:", ids)

if __name__ == "__main__":
    main()
